---
path:
  data:
    wjazzd: ../data/wjazzd.db
    csv_beats: ../data/csv_beats_test/

network:
  ip: 127.0.0.1               # Should be set to 'localhost' or 127.0.0.1
  port: 8080                  # An arbitrary number that I happen to like.

logging:
  level: 0                    # The detail level of logs (0-3).